package org.firstinspires.ftc.teamcode.opmodes.auto; // This should match the file location. This is auto generated by Android Studio

import com.qualcomm.robotcore.eventloop.opmode.OpMode;
import com.qualcomm.robotcore.eventloop.opmode.Autonomous;
import com.pedropathing.follower.Follower;
import com.pedropathing.api.PoseFactory;
import com.pedropathing.math.Pose;

import org.firstinspires.ftc.teamcode.opmodes.OpModeStorage;
import org.firstinspires.ftc.teamcode.pedro.Constants;
import org.firstinspires.ftc.teamcode.robot.RobotOpMode;

import static com.pedropathing.api.Paths.*;
import com.pedropathing.ivy.Scheduler;
import com.pedropathing.ivy.Command;

import static com.pedropathing.ivy.Scheduler.schedule;
import static com.pedropathing.ivy.commands.Commands.instant;
import static com.pedropathing.ivy.commands.Commands.waitMs;
import static com.pedropathing.ivy.commands.Commands.waitUntil;
import static com.pedropathing.ivy.groups.Groups.sequential;
import static com.pedropathing.ivy.pedro.PedroCommands.follow;

import static com.pedropathing.ivy.Scheduler.schedule;

import static java.util.concurrent.locks.LockSupport.park;

import com.pedropathing.paths.Path;
@Autonomous(name = "Test Auto", group = "Tests")
public class TESTYAUTO extends RobotOpMode {
    private Follower follower; // Add this

    // our poses
    private final PoseFactory poseFactory = PoseFactory.degrees();

    private final Pose start = poseFactory.of(56, 10, 90);
    private final Pose path1 = poseFactory.of(56, 17, 180);
    private final Pose point2 = poseFactory.of(9, 10, -179.9228);
    private final Pose point2Control1 = poseFactory.of(35, 10, 0);
    private final Pose point3Start = poseFactory.of(9, 10, 180);
    private final Pose point3 = poseFactory.of(56, 21, 90);
    private final Pose point4 = poseFactory.of(13, 40, 167.5787);
    private final Pose point4Control1 = poseFactory.of(45, 33, 0);
    private final Pose point5Start = poseFactory.of(13, 40, 168);
    private final Pose point5 = poseFactory.of(56, 21, 90);
    private final Pose point6 = poseFactory.of(15, 90, 94.509);
    private final Pose point6Control1 = poseFactory.of(19, 37, 0);

    public Path path1() {
        return line(start, path1).linear(start, path1);
    }

    public Path path2() {
        return curve(path1, point2Control1, point2).tangent();
    }

    public Path path3() {
        return line(point3Start, point3).linear(point3Start, point3);
    }

    public Path path4() {
        return curve(point3, point4Control1, point4).tangent();
    }

    public Path path5() {
        return line(point5Start, point5).linear(point5Start, point5);
    }

    public Path path6() {
        return curve(point5, point6Control1, point6).tangent();
    }
    private Command autoRoutine() {
        return sequential(
                instant(() -> robot.flywheel.setTarget(2000)),
                instant(robot.flywheel::turnOn),
                robot.intake.on(),
                waitUntil(robot.flywheel:: atTarget),
                fire(),
                follow(follower, path1()),
                // Add mechanism commands here.
                follow(follower, path2()),

                follow(follower, path3()),
                // Add mechanism commands here.
                follow(follower, path4()),

                follow(follower, path5()),
                // Add mechanism commands here.
                follow(follower, path6())
        );
    }
    private Command fire() {
        return sequential(
                instant(robot.blocker::unblock),
                waitMs(1000),
                instant(robot.blocker::block)
        );
    }


    @Override
    public void init() {
        super.init();

        robot.blocker.block();

        follower = Constants.create(hardwareMap);
        follower.setPose(start);
        follower.update();

    }

    @Override
    public void start() {
        schedule(autoRoutine());
    }

    @Override
    public void loop() {

        follower.update();
        Scheduler.execute();

    }

    @Override
    public void stop() {
        OpModeStorage.autonomousEndPose = follower.pose(); //saves your position in that file
        OpModeStorage.red = false;
        //we can add any other end state things to OpModeStorage and then also save them at this point if we need any? Probably will be useful for turret position
    }
}
